name: CI

on:
  push:
    branches-ignore:
      - 'wip-*'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron:  '0 10 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          docker run \
            --rm \
            -v $PWD:/mnt:ro dkhamsing/awesome_bot \
            -w "https://gab.com/phalcon,https://twitter.com/phalconphp,https://stackoverflow.com/questions/tagged/phalcon" \
            --allow-dupe \
            --allow-redirect \
            --skip-save-results \
            -f README.md
