name: CI

on:
  push:
    branches-ignore:
      - 'wip-*'
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron:  '0 10 * * *'

jobs:
  ci:
    strategy:
      fail-fast: false

      matrix:
        ruby: ['2.5.x']
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1

      - name: Setup Ruby Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          architecture: 'x64'

      - name: Bundle install
        run: |
          command -v bundler || gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs "$(getconf _NPROCESSORS_ONLN)" --retry 10

      - name: Run Tests
        run: bundle exec awesome_bot README.md
